#!/bin/bash
#SBATCH --job-name=Pre_process
#SBATCH --output=output.%A_%a_eyePacs.out
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=128G
#SBATCH --cpus-per-task=64
#SBATCH --gres=gpu:1         
#SBATCH -p gpu                 
#SBATCH --time=12:00:00           
#SBATCH --qos=gpu-8            

hostname
python /home/xiangjian.hou/HC701-PROJECT/preprocess/pre_process_Eyepacs.py