#!/bin/bash
#SBATCH --job-name=pre_process
#SBATCH --output=output.%A_%a_messidor2.txt
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=64G
#SBATCH --cpus-per-task=16 
#SBATCH -p cpu            
#SBATCH --time=12:00:00          
#SBATCH --qos=cpu-8


hostname
python